version: '3.3'

services:
  server:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: cd ./axolotl && bash ./train_open_orca_ru.sh 
    volumes:
      - ./:/code:cached
      - ~/.cache/huggingface/:/root/.cache/huggingface/
    user: ${CURRENT_UID}
